# Generated by Django 4.2 on 2023-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uv',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uv',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
