# Generated by Django 4.2 on 2023-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_uv_x_uv_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uv',
            name='id_esp',
            field=models.CharField(max_length=100),
        ),
    ]
